#tasks:
#  - name: Install RVM and Ruby 3.2.3
#    init: |
#      # Install RVM
#      curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
#      curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
#      curl -sSL https://get.rvm.io | bash -s stable
#
#      # Load RVM into the shell
#      source ~/.rvm/scripts/rvm
#
#      # Install Ruby 3.2.3
#      rvm install 3.2.3
#
#      # Set Ruby 3.2.3 as the default version
#      rvm use 3.2.3 --default
